font_family      Berkeley Mono
font_size        14.0

macos_option_as_alt yes
cursor_shape_unfocused hollow

# Gruvbox Dark Hard
include current-theme.conf

# cursor_trail 1
# cursor_trail_decay 0.1 0.4
# cursor_trail_start_threshold 2

hide_window_decorations yes
resize_in_steps no
macos_show_window_title_in window
