// Auto-generated by scripts/generate-limits.ts
// Do not edit manually.
// Probed models: 19 (0 failed)

export const MODEL_MAX_OUTPUT_TOKENS: Record<string, number> = {
  "deepseek-v4-flash:0731": 65536,
  "deepseek-v4-pro:0813": 65536,
  "gemma4:31b": 262144,
  "glm-5.1": 131072,
  "glm-5.2": 131072,
  "glm-5.3": 524288,
  "glm-5.3-flash": 524288,
  "gpt-oss:120b": 131072,
  "gpt-oss:20b": 131072,
  "kimi-k2.6": 262144,
  "kimi-k2.7-code": 262144,
  "kimi-k3": 524288,
  "minimax-m2.7": 131072,
  "minimax-m3": 131072,
  "mistral-large-3:675b": 262144,
  "nemotron-3-nano:30b": 131072,
  "nemotron-3-super": 65536,
  "nemotron-3-ultra": 65536,
  "qwen3.5:397b": 65536,
};
