// Auto-generated by scripts/generate-pricing.ts
// Do not edit manually.
// Generated: 2026-09-03T10:12:00.135Z
// Model count: 19

export interface ModelPrice {
  input: number;
  output: number;
  cacheRead: number;
  cacheWrite: number;
}

export const MODEL_PRICING: Record<string, ModelPrice> = {
  "deepseek-v4-flash:0731": {
    input: 0.44,
    output: 1.32,
    cacheRead: 0.014,
    cacheWrite: 0,
  },
  "deepseek-v4-pro:0813": {
    input: 1.32,
    output: 3.96,
    cacheRead: 0.044,
    cacheWrite: 0,
  },
  "gemma4:31b": { input: 0.14, output: 0.4, cacheRead: 0.05, cacheWrite: 0 },
  "glm-5.1": { input: 1, output: 3.2, cacheRead: 0.2, cacheWrite: 0 },
  "glm-5.2": { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 },
  "glm-5.3": { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 },
  "glm-5.3-flash": { input: 0.15, output: 0.5, cacheRead: 0.03, cacheWrite: 0 },
  "gpt-oss:120b": { input: 0.15, output: 0.6, cacheRead: 0.014, cacheWrite: 0 },
  "gpt-oss:20b": { input: 0.07, output: 0.3, cacheRead: 0.035, cacheWrite: 0 },
  "kimi-k2.6": { input: 0.95, output: 4, cacheRead: 0.16, cacheWrite: 0 },
  "kimi-k2.7-code": { input: 0.95, output: 4, cacheRead: 0.19, cacheWrite: 0 },
  "kimi-k3": { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 0 },
  "minimax-m2.7": { input: 0.3, output: 1.2, cacheRead: 0.06, cacheWrite: 0 },
  "minimax-m3": { input: 0.6, output: 2.4, cacheRead: 0.12, cacheWrite: 0 },
  "mistral-large-3:675b": {
    input: 0.5,
    output: 1.5,
    cacheRead: 0.5,
    cacheWrite: 0,
  },
  "nemotron-3-nano:30b": {
    input: 0.06,
    output: 0.24,
    cacheRead: 0.06,
    cacheWrite: 0,
  },
  "nemotron-3-super": {
    input: 0.015,
    output: 0.6,
    cacheRead: 0.015,
    cacheWrite: 0,
  },
  "nemotron-3-ultra": { input: 0.1, output: 3, cacheRead: 0.1, cacheWrite: 0 },
  "qwen3.5:397b": { input: 0.6, output: 3.6, cacheRead: 0.6, cacheWrite: 0 },
};
